#!/usr/bin/env bash

export CONTECO_LABEL="package.metrics-overlay - ModEco"
export CONTECO_DESCRIPTION="The ModEco metrics overlay module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="metrics_overlay"
export CONTECO_TAG="v1.0.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
