#!/usr/bin/env bash


prefix="package_$2"


executionplane --silent docker container prune --force

if [[ "package_metrics_overlay_metrics_overlay_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume rm --force package_metrics_overlay_metrics_overlay_volume
	fi
	
